---

- name: Generate terraform init file
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "{{ workdir }}/vars/servers.yml"
    - "{{ workdir }}/vars/network.yml"
  tasks:
    - name: Make prvider recipe
      template:
        src: "{{ workdir }}/templates/provider.j2"
        dest: "{{ workdir }}/recipes/provider.tf"
      tags:
        - templating
    - name: Make network recipe
      template:
        src: "{{ workdir }}/templates/network.j2"
        dest: "{{ workdir }}/recipes/network.tf"
      tags:
        - templating
    - name: Make servers recipe
      template:
        src: "{{ workdir }}/templates/servers.j2"
        dest: "{{ workdir }}/recipes/servers.tf"
      tags:
        - templating
    - name: Plan terraform
      terraform:
        project_path: "{{ workdir }}/recipes"
        state: "{{ tf_action }}"
      register: tf_output
      tags:
        - creating
